# Form implementation generated from reading ui file 'newui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(556, 685)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ScanBtn = PushButton(parent=self.centralwidget)
        self.ScanBtn.setObjectName("ScanBtn")
        self.horizontalLayout_3.addWidget(self.ScanBtn)
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.ConnectionChoiceComboBox = ComboBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConnectionChoiceComboBox.sizePolicy().hasHeightForWidth())
        self.ConnectionChoiceComboBox.setSizePolicy(sizePolicy)
        self.ConnectionChoiceComboBox.setStyleSheet("ComboBox {\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-radius: 5px;\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    padding: 5px 31px 6px 11px;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\';\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    text-align: left;\n"
"}\n"
"\n"
"ComboBox:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"ComboBox:pressed {\n"
"    background-color: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"}\n"
"\n"
"ComboBox:disabled {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"\n"
"\n"
"ComboBoxMenu>MenuActionListWidget {\n"
"    border: 1px solid rgba(0, 0, 0, 0.1);\n"
"    border-radius: 9px;\n"
"    background-color: rgb(249, 249, 249);\n"
"    outline: none;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\';\n"
"}\n"
"\n"
"ComboBoxMenu>MenuActionListWidget::item {\n"
"    margin-top: 4px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"ComboBoxMenu>MenuActionListWidget::item:disabled {\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"ComboBoxMenu>MenuActionListWidget::item:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"ComboBoxMenu>MenuActionListWidget::item:selected {\n"
"    background-color: rgba(0, 0, 0, 7);\n"
"    color: black;\n"
"}\n"
"\n"
"ComboBoxMenu>MenuActionListWidget::item:selected:active {\n"
"    background-color: rgba(0, 0, 0, 0.06);\n"
"    color: rgba(0, 0, 0, 0.7);\n"
"}")
        self.ConnectionChoiceComboBox.setText("")
        self.ConnectionChoiceComboBox.setObjectName("ConnectionChoiceComboBox")
        self.horizontalLayout_3.addWidget(self.ConnectionChoiceComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BtnImport = PushButton(parent=self.centralwidget)
        self.BtnImport.setObjectName("BtnImport")
        self.horizontalLayout_2.addWidget(self.BtnImport)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ConnectBtn = PushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConnectBtn.sizePolicy().hasHeightForWidth())
        self.ConnectBtn.setSizePolicy(sizePolicy)
        self.ConnectBtn.setMinimumSize(QtCore.QSize(120, 0))
        self.ConnectBtn.setObjectName("ConnectBtn")
        self.verticalLayout.addWidget(self.ConnectBtn)
        self.DisConnectBtn = PushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DisConnectBtn.sizePolicy().hasHeightForWidth())
        self.DisConnectBtn.setSizePolicy(sizePolicy)
        self.DisConnectBtn.setMinimumSize(QtCore.QSize(120, 0))
        self.DisConnectBtn.setObjectName("DisConnectBtn")
        self.verticalLayout.addWidget(self.DisConnectBtn)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StartBtn = PushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartBtn.sizePolicy().hasHeightForWidth())
        self.StartBtn.setSizePolicy(sizePolicy)
        self.StartBtn.setMinimumSize(QtCore.QSize(120, 0))
        self.StartBtn.setObjectName("StartBtn")
        self.horizontalLayout.addWidget(self.StartBtn)
        self.PauseBtn = PushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PauseBtn.sizePolicy().hasHeightForWidth())
        self.PauseBtn.setSizePolicy(sizePolicy)
        self.PauseBtn.setMinimumSize(QtCore.QSize(120, 20))
        self.PauseBtn.setObjectName("PauseBtn")
        self.horizontalLayout.addWidget(self.PauseBtn)
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.VersionLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.VersionLabel.setObjectName("VersionLabel")
        self.horizontalLayout.addWidget(self.VersionLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.PlainTextEdit = PlainTextEdit(parent=self.centralwidget)
        self.PlainTextEdit.setObjectName("PlainTextEdit")
        self.verticalLayout_2.addWidget(self.PlainTextEdit)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "碧蓝档案初始号工具"))
        self.ScanBtn.setText(_translate("MainWindow", "扫描"))
        self.BtnImport.setText(_translate("MainWindow", "导入脚本"))
        self.label.setText(_translate("MainWindow", "当前脚本:"))
        self.label_2.setText(_translate("MainWindow", "未连接"))
        self.ConnectBtn.setText(_translate("MainWindow", "连接"))
        self.DisConnectBtn.setText(_translate("MainWindow", "断开连接"))
        self.StartBtn.setText(_translate("MainWindow", "开始"))
        self.PauseBtn.setText(_translate("MainWindow", "暂停"))
        self.VersionLabel.setText(_translate("MainWindow", "当前版本"))
from qfluentwidgets import ComboBox, PlainTextEdit, PushButton
